- name: collect information
  hosts: localhost
  vars_files: 
    - vars.yaml
  tasks:
    - name: check configuration information
      delegate_to: localhost
      purestorage.flasharray.purefa_info:
        fa_url: "{{ fa_url1 }}"
        api_token: "{{ api_token1 }}"
        gather_subset:
          - config
      register: array_info

    - name: show ntp information
      debug:
        msg: "{{ array_info['purefa_info']['config']['ntp'] }}"
