- name: create empty hostgroups on both arrays
  hosts: localhost
  gather_facts: no
  vars_files: 
    - vars.yaml
  tasks:
    - name: create hostgroup on both arrays
      delegate_to: localhost
      purestorage.flasharray.purefa_hg:
        hostgroup: "{{ hostgroup }}"
        fa_url: "{{ item.fa_url }}"
        api_token: "{{ item.api_token }}"
        state: present
      loop:
        - { fa_url: "{{ fa_url1 }}", api_token: "{{ api_token1 }}" }
        - { fa_url: "{{ fa_url2 }}", api_token: "{{ api_token2 }}" }
