- name: create a new pod
  gather_facts: yes
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: create a new pod
      delegate_to: localhost
      purestorage.flasharray.purefa_pod:
        fa_url: "{{ fa_url1 }}"
        api_token: "{{ api_token1 }}"
        name: "{{ pod_name }}"
        state: present

