- name: stretch pod
  gather_facts: no
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: stretch the pod to the second array
      delegate_to: localhost
      purestorage.flasharray.purefa_pod:
        fa_url: "{{ fa_url1 }}"
        api_token: "{{ api_token1 }}"
        name: "{{ pod_name }}"
        stretch: "{{ stretch_target }}"
